version: '3.8'

services:
  db:
    image: postgres:14.2
    container_name: diado-do-autodidata-pg-container
    ports:
      - 8432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      TZ: 'America/Sao_Paulo'
